openapi: 3.0.1
info:
  title: Shwoop Adventure App
  description: "This is the backend for the Shwoop Adventure App"
  version: 1.0.0
paths:
  /maps:
    get:
      summary: "Gets all available maps"
      operationId: get_maps
      responses:
        200:
          description: "successful operation"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MapSummary'
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetMaps.Arn}/invocations"
        responses: {}
        httpMethod: POST
        type: aws_proxy
  /maps/{map}:
    get:
      summary: "Gets all markers for the given map"
      operationId: get_map
      parameters:
      - name: map
        in: path
        description: "Name of map"
        schema:
          type: string
        required: true
      responses:
        200:
          description: "successful operation"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Map'
        404:
          description: "map not found"
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetMap.Arn}/invocations"
        responses: {}
        httpMethod: POST
        type: aws_proxy
  /maps/{map}/beacons/{beacon}:
    get:
      summary: "Attempts to get information about the given beacon"
      operationId: get_beacon
      parameters:
      - name: map
        in: path
        description: "Name of map"
        schema:
          type: string
        required: true
      - name: beacon
        in: path
        description: "ID of the beacon"
        schema:
          type: string
        required: true
      responses:
        200:
          description: "successful operation"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Beacon'
        404:
          description: "map or beacon not found"
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetBeacon.Arn}/invocations"
        responses: {}
        httpMethod: POST
        type: aws_proxy
  /redemption-codes/{code}/:
    post:
      summary: "Gets a prize object for a redemption code"
      operationId: get_prize
      parameters:
      - in: path
        name: code
        description: "The redeemable code"
        schema:
          type: string
        required: true
      responses:
        200:
          description: "successful operation"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Prize'
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetPrize.Arn}/invocations"
        responses: {}
        httpMethod: POST
        type: aws_proxy
    delete:
      summary: "Removes a prize from the table"
      operationId: delete_prize
      security:
        - User: []
      parameters:
      - in: path
        name: code
        description: "The redeemable code"
        schema:
          type: string
        required: true
      responses:
        204:
          description: "successful operation"
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${DeletePrize.Arn}/invocations"
        responses: {}
        httpMethod: POST
        type: aws_proxy
  
  #Users
  /users/{userid}/:
    get:
      summary: "Gets the user object for an id"
      operationId: get_user
      parameters:
      - in: path
        name: userid
        description: "The user ID"
        schema:
          type: string
        required: true
      responses:
        200:
          description: "successful operation"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetUser.Arn}/invocations"
        responses: {}
        httpMethod: POST
        type: aws_proxy
    put:
      summary: "Creates a user"
      operationId: register_user
      parameters:
      - in: path
        name: userid
        description: "The user ID"
        schema:
          type: string
        required: true
      responses:
        201:
          description: "Account created."
        409:
          description: "Conflict. Account already exists."
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${RegisterUser.Arn}/invocations"
        responses: {}
        httpMethod: POST
        type: aws_proxy
  /users/{userid}/prizes:
    get:
      summary: "Gets the prizes and points of a given user"
      operationId: get_user_prizes
      responses:
        200:
          description: "Account created."
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserPrizes'
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetUserPrizes.Arn}/invocations"
        responses: {}
        httpMethod: POST
        type: aws_proxy
  /user/{userid}/redeem-treasure:
    post:
      summary: "Gets a prize for a treasure beacon"
      operationId: redeem_treasure
      security:
        - User: []
      parameters:
      - in: path
        name: userid
        description: "The User ID"
        schema:
          type: string
      - in: query
        name: beacon
        description: "The treasure beacon"
        schema:
          type: string
        required: true
      responses:
        200:
          description: "successful operation"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Prize'
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetTreasure.Arn}/invocations"
        responses: {}
        httpMethod: POST
        type: aws_proxy
  /users/challenge:
    post:
      summary: "Start a new challenge"
      operationId: start_challenge
      parameters:
      - name: beacon
        in: body
        description: "Beacon that the challenge was started from"
        schema:
          type: string
        required: false
      - name: marker
        in: body
        description: "Marker the challenge was started from"
        schema:
          type: number
        required: false
      responses:
        201:
          description: "successful operation"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Puzzle'
        404:
          description: "map or beacon not found"
          content: {}
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${StartChallenge.Arn}/invocations"
        responses: {}
        httpMethod: POST
        type: aws_proxy
    delete:
      summary: "Stop a challenge"
      operationId: stop_challenge
      parameters:
      - name: map
        in: path
        description: "The current map"
        schema:
          type: string
        required: true
      - name: challenge
        in: query
        description: "The id of the challenge being completed"
        schema:
          type: string
        required: true
      responses:
        204:
          description: "successful operation"
        404:
          description: "map or beacon not found, or challenge not started"
          content: {}
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${StopChallenge.Arn}/invocations"
        responses: {}
        httpMethod: POST
        type: aws_proxy
  /users/{userid}/challenge/finish:
    post:
      summary: "Attempt to complete a challenge"
      operationId: finish_challenge
      parameters:
      - in: path
        name: map
        description: "The current map"
        schema:
          type: string
        required: true
      - in: query
        name: challenge
        description: "The id of the challenge being completed"
        schema:
          type: string
        required: true
      - in: query
        name: beacon
        description: "The id of the beacon being used"
        schema:
          type: string
        required: true
      requestBody:
        description: "Contains the beacon of the guessed solution"
        content:
          application/json:
            schema:
              type: object
              properties:
                beacon_id:
                  type: string
      responses:
        200:
          description: "Successfully solved puzzle"
          content:
            application/json:
              schema:
                type: object
                properties:
                  prize:
                    $ref: '#/components/schemas/Prize'
        204: # This or a 400 code?
          description: "Did not solve puzzle"
          content: {}
        400:
          description: "Input body incorrect. Need a valid beacon_id"
          content: {}
        404:
          description: "map not found, or challenge not started"
          content: {}
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${FinishChallenge.Arn}/invocations"
        responses: {}
        httpMethod: POST
        type: aws_proxy
    
components:
  securitySchemes:
    User:
      type: http
      scheme: bearer
  schemas:
    MapSummary:
      type: object
      properties:
        image_url:
          type: string
          description: "Url of the map image"
        top_left:
          $ref: '#/components/schemas/Coordinate'
        bottom_right:
          $ref: '#/components/schemas/Coordinate'
    Map:
      type: object
      properties:
        markers:
          type: array
          items:
            $ref: '#/components/schemas/Marker'
    Puzzle:
      type: object
      properties:
        id:
          type: object
          description: "The id of the puzzle"
        text:
          type: string
          description: "Text of the puzzle"
        image_url:
          type: string
          description: "Url of an image related to the puzzle"
    Marker:
      type: object
      properties:
        id:
          type: integer
          description: Unique id
        location:
          $ref: '#/components/schemas/Coordinate'
        open:
          type: boolean
          default: false
          description: Whether the marker requires a connection to bluetooth (if it is open, no connection required)
      required: [id, location]
    Beacon:
      type: object
      properties:
        location:
          $ref: '#/components/schemas/Coordinate'
      oneOf:
      - type: object
        properties:
          beacon_type:
            type: string
            enum:
              - marker
          marker:
            type: integer
      - type: object
        properties:
          beacon_type:
            type: string
            enum:
              - treasure
      - type: object
        properties:
          beacon_type:
            type: string
            enum:
              - hidden
    Prize:
      type: object
      properties:
        id:
          type: string
        type:
          type: string
          enum:
          - 'points'
          - 'red-bull'
        points:
          type: number
          description: "Number of points recieved. Only present if type is 'points'"
          nullable: true
        received:
          type: string
        received_from:
          type: string
          enum: ['challenge', 'treasure']
        claimed:
          type: boolean
    UserPrizes:
      type: object
      properties:
        points:
          type: number
        prizes:
          type: array
    User:
      type: object
      properties:
        id:
          type: string
        points:
          type: number
        surveys:
          type: array
        prizes:
          type: array
        treasure:
          type: array
    Coordinate:
      type: object
      properties:
        latitude:
          type: number
          format: double
          maximum: 180
          minimum: -180
        longitude:
          type: number
          format: double
          maximum: 180
          minimum: -180
